# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# XDC: new/unity_constr.xdc

# Block Designs: bd/unity/unity.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==unity || ORIG_REF_NAME==unity}]

# IP: bd/unity/ip/unity_processing_system7_0_0/unity_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==unity_processing_system7_0_0 || ORIG_REF_NAME==unity_processing_system7_0_0}]

# IP: bd/unity/ip/unity_unity_ctrl_0_0/unity_unity_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==unity_unity_ctrl_0_0 || ORIG_REF_NAME==unity_unity_ctrl_0_0}]

# XDC: bd/unity/unity_ooc.xdc
