# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1}]

# IP: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0}]

# IP: bd/design_1/ip/design_1_inverter_0_0/design_1_inverter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_inverter_0_0 || ORIG_REF_NAME==design_1_inverter_0_0}]

# IP: bd/design_1/ip/design_1_Rotary_counter_0_0/design_1_Rotary_counter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_Rotary_counter_0_0 || ORIG_REF_NAME==design_1_Rotary_counter_0_0}]

# IP: bd/design_1/ip/design_1_Rotary_Encoder_0_0/design_1_Rotary_Encoder_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_Rotary_Encoder_0_0 || ORIG_REF_NAME==design_1_Rotary_Encoder_0_0}]

# IP: bd/design_1/ip/design_1_Debouncer_1_0/design_1_Debouncer_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_Debouncer_1_0 || ORIG_REF_NAME==design_1_Debouncer_1_0}]

# IP: bd/design_1/ip/design_1_Debouncer_2_0/design_1_Debouncer_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_Debouncer_2_0 || ORIG_REF_NAME==design_1_Debouncer_2_0}]

# IP: bd/design_1/ip/design_1_Debouncer_3_0/design_1_Debouncer_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_Debouncer_3_0 || ORIG_REF_NAME==design_1_Debouncer_3_0}]

# IP: bd/design_1/ip/design_1_PWM_generator_0_0/design_1_PWM_generator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_PWM_generator_0_0 || ORIG_REF_NAME==design_1_PWM_generator_0_0}]

# IP: bd/design_1/ip/design_1_Toggler_0_0/design_1_Toggler_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_Toggler_0_0 || ORIG_REF_NAME==design_1_Toggler_0_0}]

# IP: bd/design_1/ip/design_1_inverter_0_1/design_1_inverter_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_inverter_0_1 || ORIG_REF_NAME==design_1_inverter_0_1}]

# IP: bd/design_1/ip/design_1_Debouncer_2_1/design_1_Debouncer_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_Debouncer_2_1 || ORIG_REF_NAME==design_1_Debouncer_2_1}]

# XDC: bd/design_1/design_1_ooc.xdc
