webtalk_init -webtalk_dir /home/stefan/Dropbox/ROB_ELEC/FPGA/PWM/PWM.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2016-12-07 22:47:54" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2016.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2016.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "210779069_174157381_210622961_163" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "b92k743moe5bhr5ciuvfssqi36" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2016.3_5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "5" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Arch" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Arch Linux" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4712MQ CPU @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2300.140 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "12,000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1481111583000" -context "sdk\\\\hardware/1481111583000"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1481111583000"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1481111583000"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1481111583000"
webtalk_add_data -client sdk -key VivadoVersion -value "2016.3" -context "sdk\\\\hardware/1481111583000"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1481111583000"
webtalk_add_data -client sdk -key Device -value "7z010" -context "sdk\\\\hardware/1481111583000"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1481111583000"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1481111583000"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1481111583000"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1481111583000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1481147272658"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1481147272658"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1481147272658"
webtalk_add_data -client sdk -key DebugCount -value "8" -context "sdk\\\\bsp/1481147272658"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1481147272658"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1481147272658"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1481147272658"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1481147272658"
webtalk_transmit -clientid 2537683948 -regid "210779069_174157381_210622961_163" -xml /home/stefan/Dropbox/ROB_ELEC/FPGA/PWM/PWM.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/stefan/Dropbox/ROB_ELEC/FPGA/PWM/PWM.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/stefan/Dropbox/ROB_ELEC/FPGA/PWM/PWM.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
