# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# XDC: new/unity_constr.xdc

# Block Designs: bd/unity/unity.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==unity || ORIG_REF_NAME==unity}]

# IP: bd/unity/ip/unity_processing_system7_0_0/unity_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==unity_processing_system7_0_0 || ORIG_REF_NAME==unity_processing_system7_0_0}]

# IP: bd/unity/ip/unity_unity_ctrl_0_0/unity_unity_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==unity_unity_ctrl_0_0 || ORIG_REF_NAME==unity_unity_ctrl_0_0}]

# IP: bd/unity/ip/unity_BLDC_CONTROLLER_0_0/unity_BLDC_CONTROLLER_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==unity_BLDC_CONTROLLER_0_0 || ORIG_REF_NAME==unity_BLDC_CONTROLLER_0_0}]

# IP: bd/unity/ip/unity_xlconstant_1_0/unity_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==unity_xlconstant_1_0 || ORIG_REF_NAME==unity_xlconstant_1_0}]

# IP: bd/unity/ip/unity_PWM_generator_0_0/unity_PWM_generator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==unity_PWM_generator_0_0 || ORIG_REF_NAME==unity_PWM_generator_0_0}]

# IP: bd/unity/ip/unity_vector_splitter_0_0/unity_vector_splitter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==unity_vector_splitter_0_0 || ORIG_REF_NAME==unity_vector_splitter_0_0}]

# IP: bd/unity/ip/unity_xlconcat_0_0/unity_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==unity_xlconcat_0_0 || ORIG_REF_NAME==unity_xlconcat_0_0}]

# IP: bd/unity/ip/unity_BLDC_DIR_CTRL_0_0/unity_BLDC_DIR_CTRL_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==unity_BLDC_DIR_CTRL_0_0 || ORIG_REF_NAME==unity_BLDC_DIR_CTRL_0_0}]

# IP: bd/unity/ip/unity_OL_BLDC_Stepper_0_0/unity_OL_BLDC_Stepper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==unity_OL_BLDC_Stepper_0_0 || ORIG_REF_NAME==unity_OL_BLDC_Stepper_0_0}]

# IP: bd/unity/ip/unity_Debouncer_5_0/unity_Debouncer_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==unity_Debouncer_5_0 || ORIG_REF_NAME==unity_Debouncer_5_0}]

# IP: bd/unity/ip/unity_Toggler_0_0/unity_Toggler_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==unity_Toggler_0_0 || ORIG_REF_NAME==unity_Toggler_0_0}]

# IP: bd/unity/ip/unity_inverter_1_0/unity_inverter_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==unity_inverter_1_0 || ORIG_REF_NAME==unity_inverter_1_0}]

# IP: bd/unity/ip/unity_BLDC_STARTUP_0_0/unity_BLDC_STARTUP_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==unity_BLDC_STARTUP_0_0 || ORIG_REF_NAME==unity_BLDC_STARTUP_0_0}]

# IP: bd/unity/ip/unity_vector_mux_0_0/unity_vector_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==unity_vector_mux_0_0 || ORIG_REF_NAME==unity_vector_mux_0_0}]

# IP: bd/unity/ip/unity_Debouncer_5_1/unity_Debouncer_5_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==unity_Debouncer_5_1 || ORIG_REF_NAME==unity_Debouncer_5_1}]

# IP: bd/unity/ip/unity_inverter_0_1/unity_inverter_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==unity_inverter_0_1 || ORIG_REF_NAME==unity_inverter_0_1}]

# IP: bd/unity/ip/unity_period_smoother_0_0/unity_period_smoother_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==unity_period_smoother_0_0 || ORIG_REF_NAME==unity_period_smoother_0_0}]

# IP: bd/unity/ip/unity_vector_mux_0_1/unity_vector_mux_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==unity_vector_mux_0_1 || ORIG_REF_NAME==unity_vector_mux_0_1}]

# IP: bd/unity/ip/unity_xlconcat_0_1/unity_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==unity_xlconcat_0_1 || ORIG_REF_NAME==unity_xlconcat_0_1}]

# IP: bd/unity/ip/unity_xlslice_0_0/unity_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==unity_xlslice_0_0 || ORIG_REF_NAME==unity_xlslice_0_0}]

# IP: bd/unity/ip/unity_xlslice_0_1/unity_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==unity_xlslice_0_1 || ORIG_REF_NAME==unity_xlslice_0_1}]

# IP: bd/unity/ip/unity_xlslice_1_0/unity_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==unity_xlslice_1_0 || ORIG_REF_NAME==unity_xlslice_1_0}]

# IP: bd/unity/ip/unity_VECTOR_INV_0_0/unity_VECTOR_INV_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==unity_VECTOR_INV_0_0 || ORIG_REF_NAME==unity_VECTOR_INV_0_0}]

# IP: bd/unity/ip/unity_DIR_SENSE_0_0/unity_DIR_SENSE_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==unity_DIR_SENSE_0_0 || ORIG_REF_NAME==unity_DIR_SENSE_0_0}]

# XDC: bd/unity/unity_ooc.xdc
