set_property IOSTANDARD LVCMOS33 [get_ports rx_i]
set_property IOSTANDARD LVCMOS33 [get_ports tx_o]
set_property PACKAGE_PIN J14 [get_ports rx_i]
set_property PACKAGE_PIN H12 [get_ports tx_o]
set_property PACKAGE_PIN P15 [get_ports {leds_o[0]}]
set_property PACKAGE_PIN M14 [get_ports {leds_o[1]}]
set_property PACKAGE_PIN L13 [get_ports {leds_o[2]}]
set_property PACKAGE_PIN M15 [get_ports {leds_o[3]}]
set_property PACKAGE_PIN L12 [get_ports {leds_o[4]}]
set_property PACKAGE_PIN R12 [get_ports {leds_o[5]}]
set_property PACKAGE_PIN R13 [get_ports {leds_o[6]}]
set_property PACKAGE_PIN R15 [get_ports {leds_o[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {leds_o[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_o[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_o[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_o[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_o[2]}]

set_property IOSTANDARD LVCMOS33 [get_ports {leds_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_o[0]}]
