# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg225-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/stefan/PWM/PWM.cache/wt [current_project]
set_property parent.project_path /home/stefan/PWM/PWM.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part trenz.biz:te0726_m:part0:3.1 [current_project]
set_property ip_output_repo /home/stefan/PWM/PWM.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  /home/stefan/PWM/PWM.srcs/sources_1/new/unity_link/Synchronizer.vhd
  /home/stefan/PWM/PWM.srcs/sources_1/new/unity_link/FifoWritePort.vhd
  /home/stefan/PWM/PWM.srcs/sources_1/new/unity_link/FifoReadPort.vhd
  /home/stefan/PWM/PWM.srcs/sources_1/new/unity_link/RegFile2.vhd
  /home/stefan/PWM/PWM.srcs/sources_1/new/unity_link/FifoCtrl.vhd
  /home/stefan/PWM/PWM.srcs/sources_1/new/unity_link/pulse_gen.vhd
  /home/stefan/PWM/PWM.srcs/sources_1/new/unity_link/log_pkg.vhd
  /home/stefan/PWM/PWM.srcs/sources_1/new/unity_link/gab_link_al_subgrp.vhd
  /home/stefan/PWM/PWM.srcs/sources_1/new/unity_link/fifo_out_mux.vhd
  /home/stefan/PWM/PWM.srcs/sources_1/new/unity_link/fifo_in_mux.vhd
  /home/stefan/PWM/PWM.srcs/sources_1/new/unity_link/Fifo.vhd
  /home/stefan/PWM/PWM.srcs/sources_1/new/unity_link/checksum.vhd
  /home/stefan/PWM/PWM.srcs/sources_1/new/unity_link/util_pkg.vhd
  /home/stefan/PWM/PWM.srcs/sources_1/new/unity_link/uart_tx.vhd
  /home/stefan/PWM/PWM.srcs/sources_1/new/unity_link/uart_rx.vhd
  /home/stefan/PWM/PWM.srcs/sources_1/new/unity_link/uart_gab_link_dl_tx_fsm.vhd
  /home/stefan/PWM/PWM.srcs/sources_1/new/unity_link/uart_gab_link_dl_rx_fsm.vhd
  /home/stefan/PWM/PWM.srcs/sources_1/new/unity_link/uart_gab_link_dl_ascii_enc.vhd
  /home/stefan/PWM/PWM.srcs/sources_1/new/unity_link/uart_gab_link_dl_ascii_dec.vhd
  /home/stefan/PWM/PWM.srcs/sources_1/new/unity_link/rr_prio_enc.vhd
  /home/stefan/PWM/PWM.srcs/sources_1/new/unity_link/mod_m_counter.vhd
  /home/stefan/PWM/PWM.srcs/sources_1/new/unity_link/gab_link_al_submngr.vhd
  /home/stefan/PWM/PWM.srcs/sources_1/new/unity_link/fifo_reg.vhd
  /home/stefan/PWM/PWM.srcs/sources_1/new/unity_link/dual_fifo_mux.vhd
  /home/stefan/PWM/PWM.srcs/sources_1/new/unity_link/wb_classic_interface.vhd
  /home/stefan/PWM/PWM.srcs/sources_1/new/unity_link/uart_gab_link_dl.vhd
  /home/stefan/PWM/PWM.srcs/sources_1/new/unity_link/uart_asynch.vhd
  /home/stefan/PWM/PWM.srcs/sources_1/new/unity_link/gab_link_al_fsm.vhd
  /home/stefan/PWM/PWM.srcs/sources_1/new/unity_link/wb_slv_mem_ctrl.vhd
  /home/stefan/PWM/PWM.srcs/sources_1/new/unity_link/wb_mst_ctrl.vhd
  /home/stefan/PWM/PWM.srcs/sources_1/new/unity_link/uart_gab_link.vhd
  /home/stefan/PWM/PWM.srcs/sources_1/new/unity_link/ram_rwrw.vhd
  /home/stefan/PWM/PWM.srcs/sources_1/new/unity_link/wb_mem.vhd
  /home/stefan/PWM/PWM.srcs/sources_1/new/unity_link/uart_wb_link.vhd
  /home/stefan/PWM/PWM.srcs/sources_1/new/unity_link/clock_gen.vhd
  /home/stefan/PWM/PWM.srcs/sources_1/new/unity_link/wrap_unity.vhd
  /home/stefan/PWM/PWM.srcs/sources_1/new/unity_ctrl.vhd
}
read_ip -quiet /home/stefan/PWM/PWM.srcs/sources_1/bd/unity/ip/unity_unity_ctrl_0_0/unity_unity_ctrl_0_0.xci
set_property is_locked true [get_files /home/stefan/PWM/PWM.srcs/sources_1/bd/unity/ip/unity_unity_ctrl_0_0/unity_unity_ctrl_0_0.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

set cached_ip [config_ip_cache -export -no_bom -use_project_ipc -dir /home/stefan/PWM/PWM.runs/unity_unity_ctrl_0_0_synth_1 -new_name unity_unity_ctrl_0_0 -ip [get_ips unity_unity_ctrl_0_0]]

if { $cached_ip eq {} } {

synth_design -top unity_unity_ctrl_0_0 -part xc7z010clg225-1 -mode out_of_context

#---------------------------------------------------------
# Generate Checkpoint/Stub/Simulation Files For IP Cache
#---------------------------------------------------------
catch {
 write_checkpoint -force -noxdef -rename_prefix unity_unity_ctrl_0_0_ unity_unity_ctrl_0_0.dcp

 set ipCachedFiles {}
 write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ unity_unity_ctrl_0_0_stub.v
 lappend ipCachedFiles unity_unity_ctrl_0_0_stub.v

 write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ unity_unity_ctrl_0_0_stub.vhdl
 lappend ipCachedFiles unity_unity_ctrl_0_0_stub.vhdl

 write_verilog -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ unity_unity_ctrl_0_0_sim_netlist.v
 lappend ipCachedFiles unity_unity_ctrl_0_0_sim_netlist.v

 write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ unity_unity_ctrl_0_0_sim_netlist.vhdl
 lappend ipCachedFiles unity_unity_ctrl_0_0_sim_netlist.vhdl

 config_ip_cache -add -dcp unity_unity_ctrl_0_0.dcp -move_files $ipCachedFiles -use_project_ipc -ip [get_ips unity_unity_ctrl_0_0]
}

rename_ref -prefix_all unity_unity_ctrl_0_0_

write_checkpoint -force -noxdef unity_unity_ctrl_0_0.dcp

catch { report_utilization -file unity_unity_ctrl_0_0_utilization_synth.rpt -pb unity_unity_ctrl_0_0_utilization_synth.pb }

if { [catch {
  file copy -force /home/stefan/PWM/PWM.runs/unity_unity_ctrl_0_0_synth_1/unity_unity_ctrl_0_0.dcp /home/stefan/PWM/PWM.srcs/sources_1/bd/unity/ip/unity_unity_ctrl_0_0/unity_unity_ctrl_0_0.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub /home/stefan/PWM/PWM.srcs/sources_1/bd/unity/ip/unity_unity_ctrl_0_0/unity_unity_ctrl_0_0_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub /home/stefan/PWM/PWM.srcs/sources_1/bd/unity/ip/unity_unity_ctrl_0_0/unity_unity_ctrl_0_0_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim /home/stefan/PWM/PWM.srcs/sources_1/bd/unity/ip/unity_unity_ctrl_0_0/unity_unity_ctrl_0_0_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim /home/stefan/PWM/PWM.srcs/sources_1/bd/unity/ip/unity_unity_ctrl_0_0/unity_unity_ctrl_0_0_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}


} else {


if { [catch {
  file copy -force /home/stefan/PWM/PWM.runs/unity_unity_ctrl_0_0_synth_1/unity_unity_ctrl_0_0.dcp /home/stefan/PWM/PWM.srcs/sources_1/bd/unity/ip/unity_unity_ctrl_0_0/unity_unity_ctrl_0_0.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  file rename -force /home/stefan/PWM/PWM.runs/unity_unity_ctrl_0_0_synth_1/unity_unity_ctrl_0_0_stub.v /home/stefan/PWM/PWM.srcs/sources_1/bd/unity/ip/unity_unity_ctrl_0_0/unity_unity_ctrl_0_0_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force /home/stefan/PWM/PWM.runs/unity_unity_ctrl_0_0_synth_1/unity_unity_ctrl_0_0_stub.vhdl /home/stefan/PWM/PWM.srcs/sources_1/bd/unity/ip/unity_unity_ctrl_0_0/unity_unity_ctrl_0_0_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force /home/stefan/PWM/PWM.runs/unity_unity_ctrl_0_0_synth_1/unity_unity_ctrl_0_0_sim_netlist.v /home/stefan/PWM/PWM.srcs/sources_1/bd/unity/ip/unity_unity_ctrl_0_0/unity_unity_ctrl_0_0_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  file rename -force /home/stefan/PWM/PWM.runs/unity_unity_ctrl_0_0_synth_1/unity_unity_ctrl_0_0_sim_netlist.vhdl /home/stefan/PWM/PWM.srcs/sources_1/bd/unity/ip/unity_unity_ctrl_0_0/unity_unity_ctrl_0_0_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

}; # end if cached_ip 

if {[file isdir /home/stefan/PWM/PWM.ip_user_files/ip/unity_unity_ctrl_0_0]} {
  catch { 
    file copy -force /home/stefan/PWM/PWM.srcs/sources_1/bd/unity/ip/unity_unity_ctrl_0_0/unity_unity_ctrl_0_0_stub.v /home/stefan/PWM/PWM.ip_user_files/ip/unity_unity_ctrl_0_0
  }
}

if {[file isdir /home/stefan/PWM/PWM.ip_user_files/ip/unity_unity_ctrl_0_0]} {
  catch { 
    file copy -force /home/stefan/PWM/PWM.srcs/sources_1/bd/unity/ip/unity_unity_ctrl_0_0/unity_unity_ctrl_0_0_stub.vhdl /home/stefan/PWM/PWM.ip_user_files/ip/unity_unity_ctrl_0_0
  }
}
