set_property PACKAGE_PIN G11 [get_ports PWM_out]
set_property PACKAGE_PIN L15 [get_ports reset_in]
set_property IOSTANDARD LVCMOS33 [get_ports reset_in]
set_property IOSTANDARD LVCMOS33 [get_ports PWM_out]

set_property PACKAGE_PIN N14 [get_ports SW_A_in]
set_property PACKAGE_PIN L14 [get_ports SW_B_in]
set_property PACKAGE_PIN P15 [get_ports {counter_out[0]}]
set_property PACKAGE_PIN M14 [get_ports {counter_out[1]}]
set_property PACKAGE_PIN L13 [get_ports {counter_out[2]}]
set_property PACKAGE_PIN M15 [get_ports {counter_out[3]}]
set_property PACKAGE_PIN L12 [get_ports {counter_out[4]}]
set_property PACKAGE_PIN R12 [get_ports {counter_out[5]}]
set_property PACKAGE_PIN R13 [get_ports {counter_out[6]}]
set_property PACKAGE_PIN R15 [get_ports {counter_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {counter_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {counter_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {counter_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {counter_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {counter_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {counter_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {counter_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports SW_B_in]
set_property IOSTANDARD LVCMOS33 [get_ports SW_A_in]
set_property IOSTANDARD LVCMOS33 [get_ports {counter_out[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports SW_A_DB]
set_property IOSTANDARD LVCMOS33 [get_ports SW_B_DB]
set_property PACKAGE_PIN J14 [get_ports SW_B_DB]
set_property PACKAGE_PIN H12 [get_ports SW_A_DB]

set_property IOSTANDARD LVCMOS33 [get_ports ccw_out]
set_property IOSTANDARD LVCMOS33 [get_ports cw_out]
set_property PACKAGE_PIN G11 [get_ports ccw_out]
set_property PACKAGE_PIN G12 [get_ports cw_out]

set_property IOSTANDARD LVCMOS33 [get_ports cw_out_1]
set_property IOSTANDARD LVCMOS33 [get_ports ccw_out_1]
set_property PACKAGE_PIN N12 [get_ports ccw_out_1]
set_property PACKAGE_PIN N13 [get_ports cw_out_1]

set_property PACKAGE_PIN J15 [get_ports MOTOR_BTN_IN]
set_property PACKAGE_PIN J13 [get_ports MOTOR_INHIBIT]
set_property PACKAGE_PIN K13 [get_ports MOTOR_OUT]
set_property IOSTANDARD LVCMOS33 [get_ports MOTOR_BTN_IN]
set_property IOSTANDARD LVCMOS33 [get_ports MOTOR_INHIBIT]
set_property IOSTANDARD LVCMOS33 [get_ports MOTOR_OUT]


